#!/bin/bash

echo "CREATING NETWORK"
docker network create cassandra

echo "STARTING CONTAINER"
docker run --rm -d --name cassandra --hostname cassandra --network cassandra cassandra:3.11

echo "RUNNING SCRIPT"
docker run --rm --network cassandra -v "$(pwd)/data.cql:/scripts/data.cql" -e CQLSH_HOST=cassandra -e CQLSH_PORT=9042 nuvo/docker-cqlsh

# docker run --rm -it --network cassandra nuvo/docker-cqlsh cqlsh cassandra 9042 --cqlversion='3.4.4'

echo "FLUSHING DATA"
docker exec -it cassandra bash

# docker cp cassandra:$keyspace ./res

# docker kill cassandra
# docker network rm cassandra
